#!/usr/bin/env python3
"""
Universal Cache Launcher
========================

Reads cache_info.txt and runs the File Cache via hython.
Works on Linux, macOS, and Windows — no editing needed.

Usage:
    python run_cache.py              Run the cache
    python run_cache.py --dry-run    Print the command without running it
    python run_cache.py --help       Show this help

The script always writes a log file (cache_log.txt) in the shot root
with the command that was run, timestamps, and all output.

Generated by the Houdini Remote Render packager.
"""

# ====================================================================
#  STANDARD LIBRARY ONLY — this script must run without any
#  third-party packages on the render machine.
# ====================================================================

import argparse
import datetime
import os
import platform
import subprocess
import sys

# Reuse the shared helpers from run_render.py if present, otherwise
# define them inline.  This keeps each launcher fully standalone.


def find_shot_root():
    """Shot root is one level up from Scripts/."""
    return os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    )


def read_info_file(path):
    """Read a key=value file into a dict."""
    info = {}
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, value = line.partition("=")
            info[key.strip()] = value.strip()
    return info


def get(info, *keys, default=""):
    """Return the first matching key from info, or default."""
    for k in keys:
        if k in info:
            return info[k]
    return default


def find_hfs():
    """Find the Houdini install directory.

    Checks $HFS, then hython on PATH, then common install paths.
    """
    import glob
    import shutil

    hfs = os.environ.get("HFS", "")
    if hfs and os.path.isdir(hfs):
        return hfs

    path = shutil.which("hython")
    if path:
        real = os.path.realpath(path)
        candidate = os.path.dirname(os.path.dirname(real))
        if os.path.isdir(os.path.join(candidate, "bin")):
            return candidate

    if platform.system() == "Windows":
        base = r"C:\Program Files\Side Effects Software"
        if os.path.isdir(base):
            versions = sorted(glob.glob(os.path.join(base, "Houdini *")))
            if versions:
                return versions[-1]
    else:
        for pattern in ("/opt/hfs*", "/usr/local/hfs*"):
            matches = sorted(glob.glob(pattern))
            if matches:
                return matches[-1]

    return None


def setup_hfs_env(hfs):
    """Add Houdini binaries to the current process environment."""
    if not hfs:
        return
    os.environ["HFS"] = hfs
    os.environ["PATH"] = (
        os.path.join(hfs, "bin") + os.pathsep + os.environ.get("PATH", "")
    )


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the cache command without actually running it.",
    )
    parser.add_argument(
        "--info",
        default=None,
        help="Path to cache_info.txt (auto-detected if not given).",
    )
    args = parser.parse_args()

    # --- Find shot root and info file ---
    shot_root = find_shot_root()
    info_path = args.info or os.path.join(shot_root, "cache_info.txt")

    if not os.path.isfile(info_path):
        print(f"ERROR: cache_info.txt not found at: {info_path}")
        print("This script should be in the Scripts/ directory of a packaged shot.")
        sys.exit(1)

    info = read_info_file(info_path)

    # --- Required fields ---
    hip_file = get(info, "hipfile")
    cache_node = get(info, "cache_node")
    start = get(info, "startframe", default="1")
    end = get(info, "endframe", default=start)

    if not hip_file:
        print("ERROR: 'hipfile' not found in cache_info.txt")
        sys.exit(1)
    if not cache_node:
        print("ERROR: 'cache_node' not found in cache_info.txt")
        sys.exit(1)

    # --- Find Houdini ---
    import shutil as _shutil
    hfs = find_hfs()
    if not hfs and not _shutil.which("hython"):
        print("ERROR: Cannot find Houdini.")
        print("  Set $HFS or add hython to your PATH.")
        sys.exit(1)
    setup_hfs_env(hfs)

    # --- Build hython command ---
    #
    # hython runs a Python one-liner that:
    #   1. Loads the .hip file
    #   2. Finds the File Cache node
    #   3. Sets the frame range
    #   4. Presses the "Save to Disk" button
    #
    hip_path = os.path.join(shot_root, hip_file)

    py_code = (
        "import hou, sys; "
        f"hou.hipFile.load(r'{hip_path}'); "
        f"node = hou.node(r'{cache_node}'); "
        f"assert node, 'Node {cache_node} not found'; "
        "[node.parm(p).deleteAllKeyframes() for p in ('trange','f1','f2','f3')]; "
        f"node.parm('trange').set(1); "
        f"node.parm('f1').set({start}); "
        f"node.parm('f2').set({end}); "
        "node.parm('f3').set(1); "
        "node.parm('execute').pressButton()"
    )

    cmd = ["hython", "-c", py_code]

    # --- Open log ---
    log_path = os.path.join(shot_root, "cache_log.txt")
    log = open(log_path, "w")
    log.write(f"Cache Log\n")
    log.write(f"{'=' * 60}\n")
    log.write(f"Started: {datetime.datetime.now().isoformat()}\n")
    log.write(f"Host:    {platform.node()}\n\n")

    # Dump info file
    log.write("--- cache_info.txt ---\n")
    for k, v in info.items():
        log.write(f"  {k} = {v}\n")
    log.write("---\n\n")

    cmd_str = " ".join(cmd)
    log.write(f"Command:\n  {cmd_str}\n\n")
    log.flush()

    print(f"Cache: {get(info, 'shot_name', default='(unknown)')}")
    print(f"Frames: {start}-{end}")
    print(f"Node: {cache_node}")
    print()

    if args.dry_run:
        print("DRY RUN — would execute:")
        print(f"  {cmd_str}")
        log.write("DRY RUN — not executed.\n")
        log.close()
        return

    print(f"Command:\n  {cmd_str}")
    print()

    # --- Run ---
    t0 = datetime.datetime.now()

    process = subprocess.Popen(
        cmd,
        cwd=shot_root,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    for line in process.stdout:
        sys.stdout.write(line)
        log.write(line)
        log.flush()
    process.wait()

    elapsed = (datetime.datetime.now() - t0).total_seconds()
    log.write(f"\n{'=' * 60}\n")
    log.write(f"Finished: {datetime.datetime.now().isoformat()}\n")
    log.write(f"Elapsed:  {elapsed:.1f}s\n")
    log.write(f"Exit code: {process.returncode}\n")
    log.close()

    if process.returncode == 0:
        print(f"\nCache complete. ({elapsed:.1f}s)")
    else:
        print(f"\nCache FAILED (exit code {process.returncode}). See cache_log.txt.")

    sys.exit(process.returncode)


if __name__ == "__main__":
    main()
