#!/usr/bin/env python3
"""
Universal Orchestration Launcher
=================================

Discovers cache and render scripts in Scripts/, runs caches first
(in numbered order), then the render.  Works on any platform.

Usage:
    python run_all.py              Run everything
    python run_all.py --dry-run    Show what would run without running it
    python run_all.py --help       Show this help

Cache scripts are discovered by filename pattern: run_cache_*.py
The render script is: run_render.py

All output goes to orchestration_log.txt in the shot root.

Generated by the Houdini Remote Render packager.
"""

# ====================================================================
#  STANDARD LIBRARY ONLY
# ====================================================================

import argparse
import datetime
import glob
import os
import platform
import subprocess
import sys


def find_shot_root():
    """Shot root is one level up from Scripts/."""
    return os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    )


def discover_scripts(scripts_dir):
    """Find cache and render scripts in the Scripts/ directory.

    Discovers both .py and .sh cache scripts.  Combined cache+render
    packages generate per-cache .sh scripts (run_cache_001_sim.sh etc.)
    while standalone cache packages use run_cache.py.

    Returns (cache_scripts, render_script) where:
        cache_scripts: sorted list of (path, is_python) tuples
        render_script: (path, is_python) tuple, or None
    """
    # Cache scripts — check .py first, then .sh
    # Sorted by name (which sorts by number: 001, 002, ...)
    py_caches = sorted(glob.glob(os.path.join(scripts_dir, "run_cache_*.py")))
    sh_caches = sorted(glob.glob(os.path.join(scripts_dir, "run_cache_*.sh")))

    cache_scripts = []
    # Prefer .py when both exist for the same base name
    sh_bases = {os.path.splitext(os.path.basename(s))[0] for s in sh_caches}
    for s in py_caches:
        cache_scripts.append((s, True))
        sh_bases.discard(os.path.splitext(os.path.basename(s))[0])
    for s in sh_caches:
        if os.path.splitext(os.path.basename(s))[0] in sh_bases:
            cache_scripts.append((s, False))
    cache_scripts.sort(key=lambda x: os.path.basename(x[0]))

    # Render script — prefer .py, fall back to .sh
    render_py = os.path.join(scripts_dir, "run_render.py")
    render_sh = os.path.join(scripts_dir, "run_render.sh")
    if os.path.isfile(render_py):
        render_script = (render_py, True)
    elif os.path.isfile(render_sh):
        render_script = (render_sh, False)
    else:
        render_script = None

    return cache_scripts, render_script


def run_step(script_path, is_python, step_num, total, log, dry_run=False):
    """Run a script as a subprocess.

    Python scripts (.py) are run with the same interpreter as this script.
    Shell scripts (.sh) are run with bash.

    Returns the exit code (0 on dry run).
    """
    label = os.path.basename(script_path)
    header = f"[{step_num}/{total}] {label}"

    print(f"--- {header} ---")
    log.write(f"--- {header} ---\n")

    if is_python:
        cmd = [sys.executable, script_path]
        if dry_run:
            cmd.append("--dry-run")
    else:
        # Shell script — use bash (Linux/macOS)
        cmd = ["bash", script_path]

    cmd_str = subprocess.list2cmdline(cmd)
    log.write(f"Command: {cmd_str}\n\n")
    log.flush()

    if dry_run and not is_python:
        # Shell scripts don't have --dry-run, so just print the command
        print(f"  DRY RUN — would execute: {cmd_str}")
        log.write(f"DRY RUN — not executed.\n\n")
        return 0

    process = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    for line in process.stdout:
        sys.stdout.write(f"  {line}")
        log.write(line)
        log.flush()
    process.wait()

    log.write(f"\nExit code: {process.returncode}\n\n")
    print(f"--- {header} {'DONE' if process.returncode == 0 else 'FAILED'} ---\n")

    return process.returncode


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Pass --dry-run to each sub-script.",
    )
    args = parser.parse_args()

    # --- Discover scripts ---
    shot_root = find_shot_root()
    scripts_dir = os.path.join(shot_root, "Scripts")
    cache_scripts, render_script = discover_scripts(scripts_dir)

    total_steps = len(cache_scripts) + (1 if render_script else 0)

    if total_steps == 0:
        print("ERROR: No cache or render scripts found in Scripts/.")
        print(f"  Looked in: {scripts_dir}")
        sys.exit(1)

    # --- Open log ---
    log_path = os.path.join(shot_root, "orchestration_log.txt")
    log = open(log_path, "w")
    log.write(f"Orchestration Log\n")
    log.write(f"{'=' * 60}\n")
    log.write(f"Started: {datetime.datetime.now().isoformat()}\n")
    log.write(f"Host:    {platform.node()}\n")
    log.write(f"Steps:   {len(cache_scripts)} cache(s) + {1 if render_script else 0} render\n\n")

    print(f"=== Orchestrated Build ===")
    print(f"Steps: {len(cache_scripts)} cache(s) + {1 if render_script else 0} render")
    if args.dry_run:
        print("(DRY RUN)")
    print()

    t0 = datetime.datetime.now()
    step = 0
    final_rc = 0

    # --- Run caches in order ---
    for script_path, is_python in cache_scripts:
        step += 1
        rc = run_step(script_path, is_python, step, total_steps, log, dry_run=args.dry_run)
        if rc != 0:
            final_rc = rc
            print(f"ERROR: Cache step failed (exit code {rc}). Stopping.")
            log.write(f"ABORTED: Cache step failed.\n")
            break

    # --- Run render ---
    if final_rc == 0 and render_script:
        step += 1
        render_path, render_is_py = render_script
        final_rc = run_step(render_path, render_is_py, step, total_steps, log, dry_run=args.dry_run)

    # --- Finish ---
    elapsed = (datetime.datetime.now() - t0).total_seconds()
    log.write(f"\n{'=' * 60}\n")
    log.write(f"Finished: {datetime.datetime.now().isoformat()}\n")
    log.write(f"Elapsed:  {elapsed:.1f}s\n")
    log.write(f"Exit code: {final_rc}\n")
    log.close()

    if final_rc == 0:
        print(f"=== All {total_steps} steps complete ({elapsed:.1f}s) ===")
    else:
        print(f"=== Build FAILED (exit code {final_rc}). See orchestration_log.txt ===")

    sys.exit(final_rc)


if __name__ == "__main__":
    main()
