#!/usr/bin/env python3
"""
Universal Render Launcher
=========================

Reads render_info.txt and launches the correct renderer.
Works on Linux, macOS, and Windows — no editing needed.

Supported renderers:
    - Karma (husk)
    - Redshift (redshiftUsdCmdLine)
    - Mantra (mantra standalone via IFD files)

Usage:
    python run_render.py              Run the render
    python run_render.py --dry-run    Print the command without running it
    python run_render.py --help       Show this help

The script always writes a log file (render_log.txt) in the shot root
with the command that was run, timestamps, and all output from the
renderer.

Generated by the Houdini Remote Render packager.
"""

# ====================================================================
#  STANDARD LIBRARY ONLY — this script must run without any
#  third-party packages on the render machine.
# ====================================================================

import argparse
import datetime
import glob
import os
import platform
import shutil
import subprocess
import sys


# ====================================================================
#  LOCATING THINGS
# ====================================================================

def find_shot_root():
    """Return the shot root directory.

    The shot root is one level up from Scripts/, which is where this
    script lives.  For example:
        shot_root/Scripts/run_render.py  →  shot_root/
    """
    return os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    )


def read_info_file(path):
    """Read a key=value info file into a dict.

    Blank lines and lines starting with # are skipped.
    Values are stripped of whitespace.  All values are strings.
    """
    info = {}
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, value = line.partition("=")
            info[key.strip()] = value.strip()
    return info


def get(info, *keys, default=""):
    """Return the first matching key from info, or default.

    Handles the fact that different renderers use slightly different
    field names (e.g. 'usdfile' vs 'usd_file').
    """
    for k in keys:
        if k in info:
            return info[k]
    return default


# ====================================================================
#  FINDING RENDERER BINARIES
# ====================================================================

def find_on_path(name):
    """Find an executable on PATH.  Returns the full path, or None."""
    return shutil.which(name)


def find_hfs():
    """Find the Houdini install directory.

    Checks (in order):
        1. $HFS environment variable
        2. husk / hython on PATH (derive HFS from their location)
        3. Common install directories
    """
    # 1. Environment variable
    hfs = os.environ.get("HFS", "")
    if hfs and os.path.isdir(hfs):
        return hfs

    # 2. Find husk or hython on PATH and go up from bin/
    for binary in ("husk", "hython"):
        path = find_on_path(binary)
        if path:
            # /opt/hfs21.0/bin/husk  →  /opt/hfs21.0
            real = os.path.realpath(path)
            candidate = os.path.dirname(os.path.dirname(real))
            if os.path.isdir(os.path.join(candidate, "bin")):
                return candidate

    # 3. Common locations
    if platform.system() == "Windows":
        base = r"C:\Program Files\Side Effects Software"
        if os.path.isdir(base):
            # Pick the newest Houdini version
            versions = sorted(glob.glob(os.path.join(base, "Houdini *")))
            if versions:
                return versions[-1]
    else:
        for pattern in ("/opt/hfs*", "/usr/local/hfs*"):
            matches = sorted(glob.glob(pattern))
            if matches:
                return matches[-1]

    return None


def find_redshift():
    """Find the Redshift installation directory.

    Checks (in order):
        1. $REDSHIFT_COREDATAPATH environment variable
        2. redshiftUsdCmdLine on PATH (derive root from bin/)
        3. Common install directories
    """
    # 1. Environment variable
    rs = os.environ.get("REDSHIFT_COREDATAPATH", "")
    if rs and os.path.isdir(rs):
        return rs

    # 2. Find the binary on PATH
    path = find_on_path("redshiftUsdCmdLine")
    if path:
        real = os.path.realpath(path)
        candidate = os.path.dirname(os.path.dirname(real))
        if os.path.isdir(os.path.join(candidate, "bin")):
            return candidate

    # 3. Common locations
    if platform.system() == "Windows":
        for d in (r"C:\ProgramData\redshift", r"C:\redshift"):
            if os.path.isdir(d):
                return d
    else:
        for d in ("/usr/redshift", "/opt/redshift"):
            if os.path.isdir(d):
                return d

    return None


def setup_hfs_env(hfs):
    """Add Houdini binaries to the current process environment."""
    if not hfs:
        return
    bin_dir = os.path.join(hfs, "bin")
    os.environ["HFS"] = hfs
    os.environ["PATH"] = bin_dir + os.pathsep + os.environ.get("PATH", "")


def setup_redshift_env(rs):
    """Add Redshift binaries to the current process environment."""
    if not rs:
        return
    bin_dir = os.path.join(rs, "bin")
    os.environ["REDSHIFT_COREDATAPATH"] = rs
    os.environ["PATH"] = bin_dir + os.pathsep + os.environ.get("PATH", "")
    if platform.system() != "Windows":
        os.environ["LD_LIBRARY_PATH"] = (
            bin_dir + os.pathsep + os.environ.get("LD_LIBRARY_PATH", "")
        )


# ====================================================================
#  COMMAND BUILDERS — one per renderer
# ====================================================================

def build_karma_command(info, scenes_dir):
    """Build the husk command for Karma rendering."""

    usd_file = get(info, "usdfile", "usd_file")
    start = int(get(info, "startframe", default="1"))
    count = get(info, "framecount", default="")
    end = get(info, "endframe", default="")
    inc = int(get(info, "frameinc", default="1"))

    # Resolve frame count — Karma info uses framecount, others use endframe
    if count:
        frame_count = int(count)
    elif end:
        frame_count = int((int(end) - start) / inc) + 1
    else:
        frame_count = 1

    renderer = get(info, "renderer", default="BRAY_HdKarma")

    cmd = ["husk"]
    cmd += ["--renderer", renderer]
    cmd += ["--make-output-path"]
    cmd += ["--disable-disk-check"]
    cmd += ["--headlight", "none"]

    # Restart delegate every frame for sequences (memory management)
    if frame_count > 1:
        cmd += ["--restart-delegate", "1"]

    cmd += ["-f", str(start)]
    cmd += ["-n", str(frame_count)]
    cmd += ["-i", str(inc)]
    cmd += [os.path.join(scenes_dir, usd_file)]

    return cmd


def build_redshift_command(info, scenes_dir):
    """Build the redshiftUsdCmdLine command for Redshift rendering."""

    usd_file = get(info, "usd_file", "usdfile")
    start = int(get(info, "startframe", default="1"))
    end = int(get(info, "endframe", default=str(start)))
    inc = int(get(info, "frameinc", default="1"))
    frame_count = int((end - start) / inc) + 1

    cmd = ["redshiftUsdCmdLine"]
    cmd += [os.path.join(scenes_dir, usd_file)]
    cmd += ["-f", str(start)]
    cmd += ["-n", str(frame_count)]
    if inc != 1:
        cmd += ["-i", str(inc)]

    # GPU device
    gpu = get(info, "gpu_device", default="all")
    cmd += ["-device", gpu]

    # Optional flags
    tex_cache = get(info, "texture_cache_gb")
    if tex_cache and int(tex_cache) > 0:
        cmd += ["-texturecachebudget", tex_cache]

    ocio = get(info, "ocio_config")
    if ocio:
        cmd += ["-ocioconfig", ocio]

    return cmd


def build_mantra_command(info, ifds_dir, frame):
    """Build a single mantra command for one IFD frame.

    Mantra renders one IFD at a time, so the caller loops over frames.
    """
    ifd_pattern = get(info, "ifd_pattern")
    ifd_name = ifd_pattern % frame
    ifd_path = os.path.join(ifds_dir, ifd_name)

    cmd = ["mantra", "-V", "2a", "-j", "0", "-f", ifd_path]
    return cmd


# ====================================================================
#  DETECT RENDERER TYPE
# ====================================================================

def detect_renderer(info):
    """Determine which renderer to use from the info file.

    Returns one of: "karma", "redshift", "mantra", or None.
    """
    renderer = get(info, "renderer").lower()
    method = get(info, "method").lower()

    # Mantra: always IFD-based
    if renderer == "mantra" or method == "ifd":
        return "mantra"

    # Redshift: explicit or by command name
    if renderer == "redshift" or "redshift" in get(info, "command").lower():
        return "redshift"

    # Karma: BRAY delegates or fallback
    if "bray" in renderer or "karma" in renderer:
        return "karma"

    # If there's a USD file and no IFD pattern, assume Karma (the original)
    if get(info, "usdfile", "usd_file") and not get(info, "ifd_pattern"):
        return "karma"

    return None


# ====================================================================
#  LOGGING
# ====================================================================

def open_log(shot_root):
    """Open the render log file for writing.  Returns file handle."""
    log_path = os.path.join(shot_root, "render_log.txt")
    f = open(log_path, "w")
    f.write(f"Render Log\n")
    f.write(f"{'=' * 60}\n")
    f.write(f"Started: {datetime.datetime.now().isoformat()}\n")
    f.write(f"Host:    {platform.node()}\n")
    f.write(f"OS:      {platform.system()} {platform.release()}\n")
    f.write(f"\n")
    return f


def log_command(log, cmd, label="Command"):
    """Write a command to the log file and to stdout."""
    # list2cmdline handles quoting for paths with spaces
    cmd_str = subprocess.list2cmdline(cmd)
    log.write(f"{label}:\n  {cmd_str}\n\n")
    log.flush()
    print(f"{label}:")
    print(f"  {cmd_str}")
    print()


def log_finish(log, returncode, elapsed):
    """Write completion info to the log."""
    log.write(f"\n{'=' * 60}\n")
    log.write(f"Finished: {datetime.datetime.now().isoformat()}\n")
    log.write(f"Elapsed:  {elapsed:.1f}s\n")
    log.write(f"Exit code: {returncode}\n")
    log.flush()


# ====================================================================
#  RUNNING THINGS
# ====================================================================

def run_command(cmd, cwd, log, dry_run=False):
    """Run a command, streaming output to both stdout and the log file.

    Returns the process exit code (0 on dry run).
    """
    if dry_run:
        log_command(log, cmd, "DRY RUN — would execute")
        return 0

    log_command(log, cmd)

    # Stream output line by line so the user sees progress
    process = subprocess.Popen(
        cmd,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    for line in process.stdout:
        sys.stdout.write(line)
        log.write(line)
        log.flush()

    process.wait()
    return process.returncode


# ====================================================================
#  MAIN
# ====================================================================

def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the render command without actually running it.",
    )
    parser.add_argument(
        "--info",
        default=None,
        help="Path to render_info.txt (auto-detected if not given).",
    )
    args = parser.parse_args()

    # --- Find shot root and info file ---
    shot_root = find_shot_root()
    info_path = args.info or os.path.join(shot_root, "render_info.txt")

    if not os.path.isfile(info_path):
        print(f"ERROR: render_info.txt not found at: {info_path}")
        print("This script should be in the Scripts/ directory of a packaged shot.")
        sys.exit(1)

    info = read_info_file(info_path)
    renderer = detect_renderer(info)

    if renderer is None:
        print("ERROR: Could not determine renderer from render_info.txt.")
        print(f"  renderer = {get(info, 'renderer')}")
        print(f"  method   = {get(info, 'method')}")
        sys.exit(1)

    # --- Set up paths ---
    scenes_dir = os.path.join(shot_root, "Scenes")
    ifds_dir = os.path.join(shot_root, "IFDs")
    output_dir = os.path.join(shot_root, "Output")

    # --- Set up renderer environment ---
    if renderer in ("karma", "mantra"):
        hfs = find_hfs()
        if not hfs and not find_on_path("husk" if renderer == "karma" else "mantra"):
            print(f"ERROR: Cannot find Houdini.")
            print(f"  Set $HFS or add husk/hython to your PATH.")
            sys.exit(1)
        setup_hfs_env(hfs)

        # Mantra needs texture search path
        if renderer == "mantra":
            tex_dir = os.path.join(shot_root, "Textures")
            os.environ["HOUDINI_TEXTURE_PATH"] = tex_dir + os.pathsep + "&"

    elif renderer == "redshift":
        rs = find_redshift()
        if not rs and not find_on_path("redshiftUsdCmdLine"):
            print("ERROR: Cannot find Redshift.")
            print("  Set $REDSHIFT_COREDATAPATH or add redshiftUsdCmdLine to your PATH.")
            sys.exit(1)
        setup_redshift_env(rs)

        # Redshift doesn't auto-create output dirs
        os.makedirs(output_dir, exist_ok=True)

    # --- Open log ---
    log = open_log(shot_root)
    log.write(f"Renderer: {renderer}\n")
    log.write(f"Info file: {info_path}\n\n")

    # Dump the full info file into the log for reference
    log.write("--- render_info.txt ---\n")
    for k, v in info.items():
        log.write(f"  {k} = {v}\n")
    log.write("---\n\n")

    t0 = datetime.datetime.now()
    returncode = 0

    # --- Build and run ---
    if renderer == "karma":
        print(f"Renderer: Karma (husk)")
        cmd = build_karma_command(info, scenes_dir)
        returncode = run_command(cmd, cwd=scenes_dir, log=log, dry_run=args.dry_run)

    elif renderer == "redshift":
        print(f"Renderer: Redshift (redshiftUsdCmdLine)")
        cmd = build_redshift_command(info, scenes_dir)
        returncode = run_command(cmd, cwd=scenes_dir, log=log, dry_run=args.dry_run)

    elif renderer == "mantra":
        print(f"Renderer: Mantra (IFD standalone)")
        start = int(get(info, "startframe", default="1"))
        end = int(get(info, "endframe", default=str(start)))
        inc = int(get(info, "frameinc", default="1"))
        total = int((end - start) / inc) + 1

        for i, frame in enumerate(range(start, end + 1, inc), 1):
            print(f"Frame {frame} ({i}/{total})")
            cmd = build_mantra_command(info, ifds_dir, frame)
            rc = run_command(cmd, cwd=ifds_dir, log=log, dry_run=args.dry_run)
            if rc != 0:
                returncode = rc
                print(f"ERROR: mantra exited with code {rc} on frame {frame}")
                break

    # --- Finish ---
    elapsed = (datetime.datetime.now() - t0).total_seconds()
    log_finish(log, returncode, elapsed)
    log.close()

    if returncode == 0:
        print(f"\nRender complete. ({elapsed:.1f}s)")
    else:
        print(f"\nRender FAILED (exit code {returncode}). See render_log.txt.")

    sys.exit(returncode)


if __name__ == "__main__":
    main()
